### ISSUE TITLE
Webpack?

### ISSUE THREAD

**Issue by southpolesteve** [bustlelabs/shep#50]
Rollup didn't really work, but looks like apex has a good example for webpack

https://github.com/apex/apex/blob/master/_examples/babel-webpack/webpack.config.js

**Comment by jqyu** [comment]
Would strongly recommend webpack just because it supports multiple entry points. Been playing around with a setup where there's a monolithic repo (for shared libs, etc.), but by using multiple entry points you can create a separate bundle for each lambda function. Webpack also has some plugins for config/secret management which is a plus.

(Personally I just like using it because I like to mess around with stuff like css loaders and purescript loaders)

**Comment by southpolesteve** [comment]
@jqyu can you point me in the direction of the config stuff you like for webpack? I also stumbled across this which I think is actually a better solution than what we do now: https://github.com/hughsk/envify

**Comment by jqyu** [comment]
I've been using [`webpack.DefinePlugin`](https://webpack.github.io/docs/list-of-plugins.html#defineplugin) which is good enough for front-end stuff, since configs are sparse and it's manageable just to have an environment flag, just add you would with a C macro (which, in turn, has dead code elimination benefits, i.e. removing unreachable branches), but it seems like [`webpack.EnvironmentPlugin`](https://webpack.github.io/docs/list-of-plugins.html#environmentplugin) is what we'd need.

**Comment by southpolesteve** [comment]
Closed in Beta. We are using `webpack`! :)
